import { describe,expect,it,vi } from 'vitest';
import { readFileSync } from 'node:fs';import { join } from 'node:path';
import { buildPolicyActivity,buildWorkflowActivity,categoryTotal } from '../activity/builder';
import { loadActivity,recordActivity } from '../activity/service';
import { DEFAULT_CUSTOM_POLICY } from '../policy/profiles';import type { Finding } from '../types';
const raw=['demo.user@example.com','+91 9876543210','192.168.1.25','https://internal.local','sk_test_secret','masked-secret','screen-secret.png','blob:https://app/id','OCR full text','report content'];
const findings:Finding[]=[{id:'1',type:'Email',category:'personal',severity:'SENSITIVE',confidence:99,maskedPreview:raw[5],source:'ocr',description:raw[0],selected:true},{id:'2',type:'Internal URL',category:'network',severity:'SENSITIVE',confidence:99,maskedPreview:raw[3],source:'ocr',description:raw[2],selected:true}];
describe('safe activity boundary',()=>{it('reduces findings to allowlisted counts and no values',()=>{const event=buildWorkflowActivity('SCREENSHOT_APPROVED','SINGLE',findings,DEFAULT_CUSTOM_POLICY,4),serialized=JSON.stringify(event);expect(event.totalFindings).toBe(2);expect(buildWorkflowActivity('BATCH_ITEM_APPROVED','BATCH',findings,DEFAULT_CUSTOM_POLICY,4)).toMatchObject({eventType:'BATCH_ITEM_APPROVED',workflow:'BATCH'});expect(event.categoryCounts.email).toBe(1);expect(event.categoryCounts.internal_url).toBe(1);expect(categoryTotal(event.categoryCounts)).toBe(2);for(const value of raw)expect(serialized).not.toContain(value);for(const key of ['description','maskedPreview','filename','blob','ocr','report'])expect(serialized.toLowerCase()).not.toContain(key.toLowerCase())});it('sends only typed scalar metadata to the RPC',async()=>{const rpc=vi.fn().mockResolvedValue({error:null});await recordActivity({rpc} as never,'w',buildPolicyActivity(5));const payload=JSON.stringify(rpc.mock.calls);expect(payload).toContain('TEAM_POLICY_UPDATED');for(const value of raw)expect(payload).not.toContain(value)});it('uses a bounded newest-first workspace query',async()=>{const range=vi.fn().mockResolvedValue({data:[],error:null}),order=vi.fn(()=>({range})),eq=vi.fn(()=>({order})),select=vi.fn(()=>({eq})),from=vi.fn(()=>({select}));await loadActivity({from} as never,'w',25,999);expect(eq).toHaveBeenCalledWith('workspace_id','w');expect(order).toHaveBeenCalledWith('created_at',{ascending:false});expect(range).toHaveBeenCalledWith(25,49)})});
describe('activity database security contract',()=>{const sql=readFileSync(join(process.cwd(),'supabase','migrations','202609260003_workspace_activity.sql'),'utf8');it('allows member reads and has no direct mutation policies',()=>{expect(sql).toContain('members read workspace activity');expect(sql).toContain('is_workspace_member(workspace_id)');expect(sql).not.toMatch(/create policy[^;]+for (insert|update|delete)/i)});it('derives actor from auth.uid and rejects nonmembers',()=>{expect(sql).toContain('actor_user_id');expect(sql).toContain('auth.uid()');expect(sql).toContain('not public.is_workspace_member(target_workspace)');expect(sql.match(/create function public.record_workspace_activity\(([^)]*)\)/i)?.[1]).not.toContain('actor_user_id')});it('allowlists event/workflow/status and bounded counts',()=>{for(const event of ['SCREENSHOT_VERIFIED','SCREENSHOT_APPROVED','BATCH_ITEM_APPROVED','TEAM_POLICY_UPDATED'])expect(sql).toContain(event);expect(sql).toContain('between 0 and 10000');expect(sql).toContain("workflow_type in ('SINGLE','BATCH','POLICY')");expect(sql).toContain("review_status in ('NOT_REQUIRED','PENDING','APPROVED')")});it('is append-only and exposes no arbitrary JSON metadata',()=>{expect(sql).not.toContain('jsonb');expect(sql).toContain('No direct INSERT, UPDATE, or DELETE policy')});});
