// @vitest-environment jsdom
import { StrictMode, act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { Finding } from '../types';

const controls=vi.hoisted(()=>({scan:vi.fn(),protect:vi.fn(async()=>new Blob(['protected'],{type:'image/png'}))}));
vi.mock('../utils/image',()=>({loadImage:vi.fn(async()=>({width:640,height:360,close:vi.fn()})),protect:controls.protect}));
vi.mock('../detection/scan',()=>({scan:controls.scan,logDevelopmentScanError:vi.fn(),ScanError:class ScanError extends Error{}}));
import App from '../App';

const password:Finding={id:'password',type:'Password',category:'secret',severity:'CRITICAL',confidence:99,maskedPreview:'P•••d',source:'ocr',description:'credential',selected:true,fingerprint:'Password:test',box:{x:1,y:1,width:20,height:10}};
const internal:Finding={id:'internal',type:'Internal URL',category:'network',severity:'SENSITIVE',confidence:99,maskedPreview:'http://i•••l',source:'ocr',description:'internal',selected:true,fingerprint:'Internal URL:test',box:{x:1,y:1,width:20,height:10}};
const mounted:{root:Root;container:HTMLDivElement}[]=[];
function button(container:HTMLElement,label:string){return[...container.querySelectorAll('button')].find(item=>item.textContent?.includes(label)) as HTMLButtonElement|undefined;}
async function click(container:HTMLElement,label:string){const target=button(container,label);if(!target)throw new Error(`Missing ${label}`);await act(async()=>target.click());}
async function mount(){const container=document.createElement('div');document.body.append(container);const root=createRoot(container);mounted.push({root,container});await act(async()=>root.render(<StrictMode><App/></StrictMode>));return container;}
async function add(container:HTMLElement,files:File[]){const input=container.querySelector('input[aria-label="Add screenshots"]') as HTMLInputElement;Object.defineProperty(input,'files',{configurable:true,value:files});await act(async()=>input.dispatchEvent(new Event('change',{bubbles:true})));}

describe('batch screenshot workflow',()=>{
  beforeEach(()=>{history.replaceState({},'', '/');(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;controls.scan.mockReset();controls.protect.mockClear();let id=0;vi.spyOn(URL,'createObjectURL').mockImplementation(()=>`blob:https://example.test/${++id}`);vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});Object.defineProperty(globalThis,'ClipboardItem',{configurable:true,value:class{constructor(public data:Record<string,Blob>){}}});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{write:vi.fn().mockResolvedValue(undefined)}});});
  afterEach(async()=>{for(const entry of mounted.splice(0))await act(async()=>entry.root.unmount());document.body.textContent='';vi.restoreAllMocks();});
  it('keeps Single Screenshot as default, selects Batch Screenshots, and cleans up on mode change',async()=>{const container=await mount();expect(button(container,'Single Screenshot')?.getAttribute('aria-pressed')).toBe('true');expect(container.textContent).toContain('Your sharing checkpoint.');await click(container,'Batch Screenshots');expect(container.textContent).toContain('Protect screenshots as a batch.');await add(container,[new File(['a'],'a.png',{type:'image/png'})]);await click(container,'Single Screenshot');expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:https://example.test/1');});
  it('adds multiple same-name images while rejecting a bad file without losing valid items',async()=>{const container=await mount();await click(container,'Batch Screenshots');await add(container,[new File(['a'],'same.png',{type:'image/png'}),new File(['b'],'same.png',{type:'image/png'}),new File(['x'],'bad.txt',{type:'text/plain'})]);expect(container.querySelectorAll('.batch-card')).toHaveLength(2);expect(container.textContent).toContain('2 screenshots added; 1 rejected');expect(container.textContent?.match(/same\.png/g)?.length).toBeGreaterThanOrEqual(2);});
  it('shows no sensitive findings for an empty scan before and after a profile change',async()=>{controls.scan.mockResolvedValueOnce({findings:[]});const container=await mount();await click(container,'Batch Screenshots');await add(container,[new File(['clean'],'clean.png',{type:'image/png'})]);await click(container,'Scan All');expect(container.textContent).toContain('No sensitive findings');expect(container.textContent).toContain('0 findings');expect(container.textContent).not.toContain('Needs protection ? 0 findings');expect(container.textContent).toContain('1 No action needed');expect(button(container,'Protect Required')?.disabled).toBe(true);await click(container,'Public Documentation');expect(controls.scan).toHaveBeenCalledOnce();expect(container.textContent).toContain('No sensitive findings');expect(container.textContent).toContain('0 findings');expect(container.textContent).not.toContain('Needs protection ? 0 findings');});
  it('continues to classify BLOCK findings as needing protection',async()=>{controls.scan.mockResolvedValueOnce({findings:[password]});const container=await mount();await click(container,'Batch Screenshots');await add(container,[new File(['secret'],'secret.png',{type:'image/png'})]);await click(container,'Scan All');expect(container.textContent).toContain('Needs protection');expect(container.textContent).toContain('1 findings');expect(container.textContent).toContain('1 BLOCK');expect(button(container,'Protect Required')?.disabled).toBe(false);});
  it('isolates a failed scan, continues the sequential queue, and retries the failed item',async()=>{controls.scan.mockRejectedValueOnce(new Error('first failed')).mockResolvedValueOnce({findings:[internal]}).mockResolvedValueOnce({findings:[password]});const container=await mount();await click(container,'Batch Screenshots');await add(container,[new File(['a'],'a.png',{type:'image/png'}),new File(['b'],'b.png',{type:'image/png'})]);await click(container,'Scan All');expect(controls.scan).toHaveBeenCalledTimes(2);expect(container.textContent).toContain('Failed');expect(container.textContent).toContain('Needs protection');await click(container,'Retry Failed');expect(controls.scan).toHaveBeenCalledTimes(3);expect(container.textContent).not.toContain('This screenshot could not be scanned');});
  it('reevaluates scanned findings without OCR and invalidates Ready when the profile changes',async()=>{controls.scan.mockResolvedValueOnce({findings:[internal]}).mockResolvedValueOnce({findings:[]});const container=await mount();await click(container,'Batch Screenshots');await click(container,'Bug Report / QA');await add(container,[new File(['a'],'a.png',{type:'image/png'})]);await click(container,'Scan All');expect(container.textContent).toContain('0 PROTECT · 1 WARN');expect(controls.scan).toHaveBeenCalledOnce();await click(container,'Protect Required');expect(container.textContent).toContain('1 Ready');await click(container,'Public Documentation');expect(controls.scan).toHaveBeenCalledTimes(2);expect(container.textContent).toContain('0 Ready');expect(container.textContent).toContain('1 PROTECT');expect(button(container,'Download Ready Images')?.disabled).toBe(true);});
  it('protects and freshly verifies each item, exports and copies only verified output',async()=>{controls.scan.mockResolvedValueOnce({findings:[password]}).mockResolvedValueOnce({findings:[password]}).mockResolvedValueOnce({findings:[]}).mockResolvedValueOnce({findings:[password]});const anchor=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});const write=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,'clipboard',{configurable:true,value:{write}});const container=await mount();await click(container,'Batch Screenshots');await add(container,[new File(['a'],'safe.png',{type:'image/png'}),new File(['b'],'unsafe.png',{type:'image/png'})]);await click(container,'Scan All');await click(container,'Protect Required');expect(controls.protect).toHaveBeenCalledTimes(2);expect(controls.scan).toHaveBeenCalledTimes(4);expect(container.textContent).toContain('1 Ready');expect(container.textContent).toContain('1 Need attention');await click(container,'Download Ready Images');expect(anchor).toHaveBeenCalledOnce();const readyCard=[...container.querySelectorAll('.batch-card')].find(card=>card.textContent?.includes('Ready')) as HTMLElement;await act(async()=> (readyCard.querySelector('.batch-card-main') as HTMLButtonElement).click());await click(container,'Copy Safe Image');expect(write).toHaveBeenCalledOnce();const copied=(write.mock.calls[0][0][0] as {data:Record<string,Blob>}).data['image/png'];expect(copied).toBeInstanceOf(Blob);});
  it('removes one item, clears all items, and revokes only their owned URLs',async()=>{const container=await mount();await click(container,'Batch Screenshots');await add(container,[new File(['a'],'a.png',{type:'image/png'}),new File(['b'],'b.png',{type:'image/png'})]);const firstRemove=container.querySelector('button[aria-label="Remove a.png"]') as HTMLButtonElement;await act(async()=>firstRemove.click());expect(container.querySelectorAll('.batch-card')).toHaveLength(1);expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:https://example.test/1');expect(URL.revokeObjectURL).not.toHaveBeenCalledWith('blob:https://example.test/2');await click(container,'Clear Batch');expect(container.querySelectorAll('.batch-card')).toHaveLength(0);expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:https://example.test/2');});
  it('does not write a late scan result into a cleared batch',async()=>{let finish!:(value:{findings:Finding[]})=>void;controls.scan.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));const container=await mount();await click(container,'Batch Screenshots');await add(container,[new File(['a'],'a.png',{type:'image/png'})]);const running=click(container,'Scan All');await act(async()=>button(container,'Clear Batch')?.click());await act(async()=>finish({findings:[password]}));await running;expect(container.querySelectorAll('.batch-card')).toHaveLength(0);expect(container.textContent).not.toContain('Password');});


});
