// @vitest-environment jsdom
import {StrictMode,act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {Shell} from '../app/SaaSApp';
import type {WorkspaceRole} from '../workspace/types';
import type {Policy} from '../policy/types';

const policy:Policy={credentials:'BLOCK',email:'PROTECT',phone:'PROTECT',internalIp:'PROTECT',internalUrl:'PROTECT',publicUrl:'ALLOW',qr:'WARN',metadata:'WARN'};
const mounted:{root:Root;container:HTMLDivElement}[]=[];
function button(c:HTMLElement,label:string){return[...c.querySelectorAll('button')].find(item=>item.textContent===label) as HTMLButtonElement|undefined}
async function click(c:HTMLElement,label:string){const target=button(c,label);if(!target)throw new Error('Missing '+label);await act(async()=>target.click())}
function client(role:WorkspaceRole){const range=vi.fn().mockResolvedValue({data:[],error:null}),order=vi.fn(()=>({range})),eq=vi.fn(()=>({order})),select=vi.fn(()=>({eq}));return{from:vi.fn(()=>({select})),rpc:vi.fn(async(name:string)=>name==='can_manage_workspace'?{data:role!=='member',error:null}:name==='list_workspace_members'?{data:[{user_id:'owner',display_name:'Workspace owner',email:'owner@example.com',role:'owner'},{user_id:'member',display_name:'Workspace member',email:'member@example.com',role:'member'}],error:null}:{data:[],error:null}),auth:{signOut:vi.fn()}} as never}
async function render(role:WorkspaceRole){const container=document.createElement('div');document.body.append(container);const root=createRoot(container);mounted.push({root,container});await act(async()=>root.render(<StrictMode><Shell client={client(role)} session={{user:{email:`${role}@example.com`}} as never} workspace={{id:'workspace',name:'Acme Security',createdBy:'owner',role}} teamPolicy={{workspaceId:'workspace',policy,version:7,updatedAt:'now',updatedBy:'owner'}} onPolicyChange={()=>{}}/></StrictMode>));return container}
describe('authenticated Console shell',()=>{
 beforeEach(()=>{(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true});
 afterEach(async()=>{for(const item of mounted.splice(0))await act(async()=>item.root.unmount());document.body.textContent=''});
 it('opens on the real-data dashboard with the complete primary navigation',async()=>{const c=await render('owner');expect(c.textContent).toContain('DASHBOARD');expect(c.textContent).toContain('Acme Security');expect(c.textContent).toContain('Active Team Policyv7');expect(c.textContent).toContain('Approved for sharing');expect(c.querySelectorAll('.dashboard-header .role-badge')).toHaveLength(0);expect(c.querySelectorAll('.saas-shell-header .role-badge')).toHaveLength(1);expect(c.textContent).toContain('SafeShare Agent protection');expect(c.textContent).toContain('CaptureCheckProtectVerifyShare');const labels=[...c.querySelectorAll('.saas-shell-header nav button')].map(item=>item.textContent);expect(labels).toEqual(['Dashboard','Team','Policy','Activity','Web Scanner','Settings']);expect(labels).not.toContain('Batch')});
 it('shows management actions to owners and keeps the roster and invitations on Team',async()=>{const c=await render('owner');expect(button(c,'Manage Team Policy')).toBeTruthy();expect(button(c,'Invite teammate')).toBeTruthy();await click(c,'Team');expect(c.textContent).toContain('Workspace Members');expect(c.textContent).toContain('Workspace owner');expect(c.textContent).toContain('Workspace member');expect(c.textContent).toContain('Pending invitations');expect(button(c,'Invite member')).toBeTruthy()});
 it('shows authorized Console actions to admins',async()=>{const c=await render('admin');expect(button(c,'Manage Team Policy')).toBeTruthy();expect(button(c,'Invite teammate')).toBeTruthy();await click(c,'Policy');await act(async()=>{});expect(button(c,'Save team policy')).toBeTruthy();expect([...c.querySelectorAll('.team-policy select')].every(item=>!(item as HTMLSelectElement).disabled)).toBe(true)});
 it('keeps members organization-managed and read-only',async()=>{const c=await render('member');expect(c.textContent).toContain('Your organization manages the protection policy');expect(button(c,'Manage Team Policy')).toBeUndefined();expect(button(c,'Manage Team')).toBeUndefined();expect(button(c,'Open Web Scanner')).toBeTruthy();await click(c,'Policy');await act(async()=>{});expect(c.textContent).toContain('Team Policy v7');expect(c.textContent).toContain('Managed by your organization. Your access is read-only.');expect(button(c,'Save team policy')).toBeUndefined();expect([...c.querySelectorAll('.team-policy select')].every(item=>(item as HTMLSelectElement).disabled)).toBe(true)});
 it('keeps single and batch workflows inside Web Scanner',async()=>{const c=await render('member');await click(c,'Web Scanner');expect(c.textContent).toContain('Review a screenshot in your browser');expect(button(c,'Single Screenshot')).toBeTruthy();expect(button(c,'Batch Screenshots')).toBeTruthy();await click(c,'Batch Screenshots');expect(c.textContent).toContain('Protect multiple screenshots')});
});
