// @vitest-environment jsdom
import { act } from 'react';
import { createRoot,type Root } from 'react-dom/client';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { InviteManager } from '../invitations/InviteManager';
import { AuthForm } from '../auth/AuthForm';

const token='b'.repeat(64);let roots:Root[]=[];
function setValue(input:HTMLInputElement|HTMLSelectElement,value:string){Object.getOwnPropertyDescriptor(input instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('change',{bubbles:true}));input.dispatchEvent(new Event('input',{bubbles:true}));}
async function render(role:'owner'|'admin'|'member',rpc:ReturnType<typeof vi.fn>){const container=document.createElement('div');document.body.append(container);const root=createRoot(container);roots.push(root);await act(async()=>{root.render(<InviteManager client={{rpc} as never} workspace={{id:'w',name:'Company',createdBy:'u',role}}/>);await Promise.resolve()});return container}
function button(container:HTMLElement,label:string){return[...container.querySelectorAll('button')].find(item=>item.textContent===label) as HTMLButtonElement|undefined}
describe('invitation management UI',()=>{
 beforeEach(()=>{(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true});
 afterEach(async()=>{for(const root of roots.splice(0))await act(async()=>root.unmount());document.body.textContent='';vi.restoreAllMocks()});
 it('hides invitation management from members',async()=>{const rpc=vi.fn();const container=await render('member',rpc);expect(container.textContent).toBe('');expect(rpc).not.toHaveBeenCalled()});
 it.each([['owner',true],['admin',false]] as const)('shows permitted role options for %s',async(role,canInviteAdmin)=>{const rpc=vi.fn().mockResolvedValue({data:[],error:null});const container=await render(role,rpc);await act(async()=>button(container,'Invite member')!.click());const options=[...container.querySelectorAll('option')].map(item=>item.textContent);expect(options).toContain('Member');expect(options.includes('Admin')).toBe(canInviteAdmin)});
 it('creates an invitation and copies its transient link',async()=>{const rpc=vi.fn(async(name:string)=>name==='list_workspace_invitations'?{data:[],error:null}:{data:{invitation_id:'i',invite_token:token,expires_at:'later'},error:null});const writeText=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText}});const container=await render('owner',rpc);await act(async()=>button(container,'Invite member')!.click());setValue(container.querySelector('input[type=email]')!,'Pilot@Example.com');await act(async()=>{(container.querySelector('form') as HTMLFormElement).dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await Promise.resolve();await Promise.resolve()});expect(container.textContent).toContain('Invitation created.');expect(container.textContent).not.toContain(token);await act(async()=>button(container,'Copy invite link')!.click());expect(writeText).toHaveBeenCalledWith(location.origin+'/invite/'+token);expect(container.textContent).toContain('Invite link copied.')});
 it('shows a temporary manual-copy field only after clipboard failure',async()=>{const rpc=vi.fn(async(name:string)=>name==='list_workspace_invitations'?{data:[],error:null}:{data:{invitation_id:'i',invite_token:token,expires_at:'later'},error:null});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:vi.fn().mockRejectedValue(new Error('denied'))}});const container=await render('owner',rpc);await act(async()=>button(container,'Invite member')!.click());setValue(container.querySelector('input[type=email]')!,'pilot@example.com');await act(async()=>{(container.querySelector('form') as HTMLFormElement).dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await Promise.resolve();await Promise.resolve()});await act(async()=>button(container,'Copy invite link')!.click());expect((container.querySelector('input[readonly]') as HTMLInputElement).value).toContain(token)});
 it('renders pending and expired invitations without token data and can revoke pending',async()=>{let lists=0;const rpc=vi.fn(async(name:string)=>{if(name==='list_workspace_invitations'){lists++;return{data:lists===1?[{id:'p',email:'pilot@example.com',role:'member',status:'pending',created_at:'now',expires_at:'2099-01-01'},{id:'e',email:'old@example.com',role:'member',status:'expired',created_at:'then',expires_at:'2020-01-01'}]:[],error:null}}return{data:true,error:null}});const container=await render('owner',rpc);expect(container.textContent).toContain('pilot@example.com');expect(container.textContent).toContain('Expired');expect(container.textContent).not.toContain(token);await act(async()=>{button(container,'Revoke')!.click();await Promise.resolve();await Promise.resolve()});expect(rpc).toHaveBeenCalledWith('revoke_workspace_invitation',{target_invitation:'p'})});
});

describe('invitation authentication redirect',()=>{
 it('uses the invite route for signup confirmation without changing the default flow',async()=>{const signUp=vi.fn().mockResolvedValue({data:{session:null},error:null}),container=document.createElement('div'),root=createRoot(container);roots.push(root);await act(async()=>root.render(<AuthForm client={{auth:{signUp}} as never} mode="signup" invitationToken={token} onNavigate={()=>{}}/>));const inputs=container.querySelectorAll('input');setValue(inputs[0],'Pilot');setValue(inputs[1],'pilot@example.com');setValue(inputs[2],'password123');await act(async()=>{(container.querySelector('form') as HTMLFormElement).dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await Promise.resolve()});expect(signUp).toHaveBeenCalledWith(expect.objectContaining({options:expect.objectContaining({emailRedirectTo:window.location.origin+'/invite/'+token})}))});
});
