// @vitest-environment jsdom
import {act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {PublicSite} from '../app/PublicSite';
const mounted:{root:Root;container:HTMLDivElement}[]=[];
async function render(){const container=document.createElement('div');document.body.append(container);const root=createRoot(container);mounted.push({root,container});const onNavigate=vi.fn();await act(async()=>root.render(<PublicSite onNavigate={onNavigate}/>));return{container,onNavigate}}
describe('public SafeShare website',()=>{
 afterEach(async()=>{for(const item of mounted.splice(0))await act(async()=>item.root.unmount());document.body.textContent=''});
 it('presents a six-section private-pilot homepage with concise hero copy',async()=>{const{container}=await render();expect(container.querySelectorAll('main > section')).toHaveLength(6);expect(container.querySelector('h1')?.textContent).toBe('Stop sensitive screenshots before they leave your company.');expect(container.textContent).toContain('SafeShare checks screenshots locally, protects sensitive information, and verifies the protected image before employees share it.');expect(container.textContent).toContain('Currently available through controlled Windows private pilots.');expect(container.querySelector('.public-hero a[href="#how"]')?.textContent).toBe('See How It Works')});
 it('shows only the concise risk examples and one workflow',async()=>{const{container}=await render();for(const risk of ['API keys','Customer information','Internal URLs','Credentials'])expect(container.textContent).toContain(risk);expect(container.textContent).toContain('One screenshot can expose more than expected.');expect(container.textContent).toContain('From screenshot to safer share.');for(const step of ['CAPTURE','CHECK','PROTECT','VERIFY','SHARE'])expect(container.textContent).toContain(step);for(const copy of ['Screenshot taken','Checked locally','Sensitive data protected','Protected image rescanned','Employee approves'])expect(container.textContent).toContain(copy);expect(container.querySelectorAll('.workflow-steps')).toHaveLength(1)});
 it('keeps two primary product cards and concise privacy boundaries',async()=>{const{container}=await render();expect(container.querySelectorAll('.product-cards > article')).toHaveLength(2);expect(container.textContent).toContain('SafeShare Agent');expect(container.textContent).toContain('Checks screenshots locally before sharing.');expect(container.textContent).toContain('SafeShare Console');expect(container.textContent).toContain('Manage Team Policy and view privacy-safe workflow activity.');expect(container.textContent).toContain('A browser-based Web Scanner is available for occasional manual workflows.');for(const point of ["Screenshot processing stays on the employee's device.",'Company sharing policy is centrally managed.','Console receives privacy-safe workflow activity.'])expect(container.textContent).toContain(point)});
 it('uses the existing zero-cost pilot contact mechanism without a form',async()=>{const{container}=await render();const pilot=[...container.querySelectorAll('a')].filter(link=>link.textContent==='Start Private Pilot');expect(pilot).toHaveLength(2);expect(pilot.every(link=>link.getAttribute('href')?.startsWith('mailto:?subject=SafeShare'))).toBe(true);expect(container.querySelector('form')).toBeNull()});
 it('routes Company Sign In and preserves application route branches',async()=>{const{container,onNavigate}=await render();const signIn=[...container.querySelectorAll('button')].find(button=>button.textContent==='Company Sign In')!;await act(async()=>signIn.click());expect(onNavigate).toHaveBeenCalledWith('/login');const source=readFileSync(join(process.cwd(),'src','app','SaaSApp.tsx'),'utf8');expect(source).toContain("if(path==='/login')");expect(source).toContain("if(path==='/signup')");expect(source).toContain("path.match(/^\\/invite\\/([0-9a-f]{64})$/)");expect(source).toContain('return <PublicSite onNavigate={navigate}/>');expect(source).toContain('return <Shell client={client}')});
});