// @vitest-environment jsdom
import { describe, expect, it, vi } from 'vitest';
import type { Finding } from '../types';
import { PROFILES } from '../policy/profiles';
import { buildBatchReport, buildSingleReport } from '../report/buildReport';
import { createReportPdf, reportText, startReportDownload } from '../report/generateReport';
import { createBatchItem } from '../batch/model';

const raw=['sk_test_safeshare_8H2K9M4P7Q','ananya.demo@example.com','+91 9876543210','192.168.1.25','http://192.168.1.25/admin','Password_NotReal_123','token-secret-value','postgresql://user:pass@host/db','full OCR line with secrets'];
const types=['API Key','Email','Phone','Internal IP','Internal URL','Password','Access Token','Database Connection String','QR code'];
const findings:Finding[]=types.map((type,index)=>({id:`f${index}`,type,category:index<1||index>4?'secret':index<3?'personal':index<5?'network':'qr',severity:index===8?'REVIEW':'CRITICAL',confidence:99,maskedPreview:raw[index]??raw[8],description:`Detected ${raw[index]??raw[8]}`,selected:index!==8,fingerprint:`${type}:${raw[index]??raw[8]}`} as Finding));
const now=new Date('2026-09-25T10:00:00Z'),random=()=>0.25;

describe('privacy report safe data and PDF generation',()=>{
  it('builds a current single report with counts, policy, verification, and approval',()=>{const report=buildSingleReport({profile:'Client Sharing',workflowStatus:'Approved for sharing',findings,policy:PROFILES.client.policy,selectedForProtection:8,verifiedRemoved:8,verificationCurrent:true,verificationPassed:true,verifiedFindings:[],approved:true,now,random});expect(report.info.profile).toBe('Client Sharing');expect(report.info.workflowStatus).toBe('Approved for sharing');expect(report.info.findings.find(row=>row.label==='API Key')?.count).toBe(1);expect(report.info.actions.BLOCK).toBeGreaterThan(0);expect(report.info.verification).toBe('Passed');expect(report.info.review).toBe('Approved');});
  it('excludes every raw value, OCR text, filename, and image URL from safe data and rendered text',()=>{const report=buildSingleReport({profile:'Client Sharing',workflowStatus:'Needs protection',findings,policy:PROFILES.client.policy,selectedForProtection:8,verifiedRemoved:0,verificationCurrent:false,verificationPassed:false,verifiedFindings:[],approved:false,now,random});const serialized=JSON.stringify(report)+reportText(report);for(const value of raw)expect(serialized).not.toContain(value);expect(serialized).not.toContain('blob:https://example.test/image');expect(serialized).not.toContain('customer-password-screen.png');expect(serialized).toContain('API Key: 1');expect(serialized).toContain('cannot guarantee');expect(serialized).not.toContain('guaranteed safe');});
  it('does not report stale verification or invalidated approval as passed or approved',()=>{const report=buildSingleReport({profile:'Public Documentation',workflowStatus:'Needs protection',findings,policy:PROFILES.public.policy,selectedForProtection:8,verifiedRemoved:8,verificationCurrent:false,verificationPassed:true,verifiedFindings:[],approved:true,now,random});expect(report.info.profile).toBe('Public Documentation');expect(report.info.verification).toBe('Not run');expect(report.info.review).toBe('Not available');});
  it('represents zero findings without claiming safety',()=>{const report=buildSingleReport({profile:'Client Sharing',workflowStatus:'No sensitive findings',findings:[],policy:PROFILES.client.policy,selectedForProtection:0,verifiedRemoved:0,verificationCurrent:false,verificationPassed:false,verifiedFindings:[],approved:false,now,random});const text=reportText(report);expect(text).toContain('No findings detected');expect(text).toContain('No sensitive findings');expect(text).toContain('cannot guarantee');});
  it('builds batch aggregates and safe per-image identifiers without filenames',()=>{const verified=new Blob(['verified']),first={...createBatchItem(new File(['x'],'secret-customer-name.png',{type:'image/png'}),'blob:original',100,100),status:'ready' as const,findings:[findings[0]],outputBlob:verified,outputUrl:'blob:verified',verification:{checks:[],unresolved:[],reviewCount:0,ready:true},verifiedFindings:[],approvedOutput:verified},second={...createBatchItem(new File(['x'],'internal-host.png',{type:'image/png'}),'blob:second',100,100),status:'awaiting-review' as const,findings:[findings[4]],outputBlob:new Blob(),outputUrl:'blob:protected',verification:{checks:[],unresolved:[],reviewCount:0,ready:true},verifiedFindings:[],approvedOutput:null};const report=buildBatchReport({profile:'Public Documentation',items:[first,second],policy:PROFILES.public.policy,now,random});expect(report.approved).toBe(1);expect(report.awaitingReview).toBe(1);expect(report.rows.map(row=>row.item)).toEqual(['Screenshot 01','Screenshot 02']);expect(report.rows[0].verification).toBe('Passed');expect(report.rows[1].review).toBe('Awaiting review');const serialized=JSON.stringify(report)+reportText(report);expect(serialized).not.toContain('secret-customer-name.png');expect(serialized).not.toContain('internal-host.png');expect(serialized).not.toContain('blob:');});
  it('creates a local PDF and starts a safe-named browser download',async()=>{const report=buildSingleReport({profile:'Client Sharing',workflowStatus:'Awaiting review',findings:[findings[0]],policy:PROFILES.client.policy,selectedForProtection:1,verifiedRemoved:1,verificationCurrent:true,verificationPassed:true,verifiedFindings:[],approved:false,now,random});const pdf=createReportPdf(report);expect(pdf.type).toBe('application/pdf');expect(await pdf.text()).toContain('%PDF-1.4');const create=vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:report'),click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});expect(startReportDownload(report,'safeshare-privacy-report.pdf')).toBe('blob:report');expect(create).toHaveBeenCalledOnce();expect(click).toHaveBeenCalledOnce();create.mockRestore();click.mockRestore();});
});
