// @vitest-environment jsdom
import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { describe, expect, it, vi } from 'vitest';
import { DEFAULT_CUSTOM_POLICY } from '../policy/profiles';
import { TeamPolicy } from '../workspace/TeamPolicy';
const value={workspaceId:'w',policy:DEFAULT_CUSTOM_POLICY,version:2,updatedAt:'now',updatedBy:'u'};
async function render(role:'owner'|'admin'|'member',rpc=vi.fn(),onActivity?:()=>Promise<void>){const container=document.createElement('div');document.body.append(container);const root=createRoot(container);await act(async()=>root.render(<TeamPolicy client={{rpc} as never} workspace={{id:'w',name:'Team',createdBy:'u',role}} value={value} onChange={()=>{}} onActivity={onActivity}/>));return{container,root,rpc}}
describe('Team Policy permissions UI',()=>{
 it('renders every category as a separate label and select group',async()=>{const{container,root}=await render('member');const labels=[...container.querySelectorAll('.team-policy .custom-policy label')];expect(labels).toHaveLength(8);expect(labels.every(label=>label.querySelectorAll('select').length===1&&!!label.querySelector('span')?.textContent)).toBe(true);expect(new Set(labels.map(label=>label.textContent))).toHaveLength(8);await act(async()=>root.unmount())}); it('renders members read-only with no save action',async()=>{const{container,root,rpc}=await render('member');expect(container.textContent).toContain('Managed by your workspace. Your access is read-only.');expect([...container.querySelectorAll('select')].every(item=>item.disabled)).toBe(true);expect(container.textContent).not.toContain('Save team policy');expect(rpc).not.toHaveBeenCalled();await act(async()=>root.unmount())});
 it.each(['owner','admin'] as const)('allows %s to edit and save through the authorized RPC',async role=>{const rpc=vi.fn().mockResolvedValue({data:{workspace_id:'w',policy:{...DEFAULT_CUSTOM_POLICY,email:'WARN'},version:3,updated_at:'later',updated_by:'u'},error:null});const{container,root}=await render(role,rpc);const select=container.querySelector('select')!;await act(async()=>{select.value='WARN';select.dispatchEvent(new Event('change',{bubbles:true}))});const save=[...container.querySelectorAll('button')].find(button=>button.textContent==='Save team policy')!;expect(save.disabled).toBe(false);await act(async()=>{save.click();await Promise.resolve()});expect(rpc).toHaveBeenCalledOnce();await act(async()=>root.unmount())});
 it('records policy activity only after the server confirms the update',async()=>{const activity=vi.fn().mockResolvedValue(undefined),rpc=vi.fn().mockResolvedValue({data:{workspace_id:'w',policy:{...DEFAULT_CUSTOM_POLICY,email:'WARN'},version:3,updated_at:'later',updated_by:'u'},error:null});const{container,root}=await render('owner',rpc,activity);const select=container.querySelector('select')!;await act(async()=>{select.value='WARN';select.dispatchEvent(new Event('change',{bubbles:true}))});await act(async()=>{[...container.querySelectorAll('button')].find(button=>button.textContent==='Save team policy')!.click();await Promise.resolve()});expect(activity).toHaveBeenCalledWith(expect.objectContaining({eventType:'TEAM_POLICY_UPDATED',policyVersion:3}));await act(async()=>root.unmount())});});
