import { describe, expect, it, vi } from 'vitest';
import { DEFAULT_CUSTOM_POLICY } from '../policy/profiles';
import { loadWorkspacePolicy, saveWorkspacePolicy } from '../workspace/policyService';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const row={workspace_id:'workspace-1',policy:DEFAULT_CUSTOM_POLICY,version:3,updated_at:'2026-09-26T00:00:00Z',updated_by:'user-1'};
function loadClient(result:unknown){const single=vi.fn().mockResolvedValue(result),eq=vi.fn(()=>({single})),select=vi.fn(()=>({eq})),from=vi.fn(()=>({select}));return{client:{from} as never,from,select,eq,single}}
describe('workspace team policy service',()=>{
 it('loads and validates a policy for the requested workspace',async()=>{const mock=loadClient({data:row,error:null});expect(await loadWorkspacePolicy(mock.client,'workspace-1')).toEqual({workspaceId:'workspace-1',policy:DEFAULT_CUSTOM_POLICY,version:3,updatedAt:row.updated_at,updatedBy:'user-1'});expect(mock.eq).toHaveBeenCalledWith('workspace_id','workspace-1')});
 it('fails closed for load errors and malformed policies',async()=>{await expect(loadWorkspacePolicy(loadClient({data:null,error:{}}).client,'w')).rejects.toThrow('could not be loaded');await expect(loadWorkspacePolicy(loadClient({data:{...row,policy:{credentials:'ALLOW'}}}).client,'w')).rejects.toThrow('invalid')});
 it('saves only workspace id, policy rules, and expected version',async()=>{const rpc=vi.fn().mockResolvedValue({data:{...row,version:4},error:null});await saveWorkspacePolicy({rpc} as never,'workspace-1',DEFAULT_CUSTOM_POLICY,3);expect(rpc).toHaveBeenCalledWith('update_workspace_policy',{target_workspace:'workspace-1',new_policy:DEFAULT_CUSTOM_POLICY,expected_version:3});const payload=JSON.stringify(rpc.mock.calls);for(const forbidden of ['Blob','maskedPreview','OCR','finding','image','password','secret value'])expect(payload).not.toContain(forbidden)});
 it('rejects malformed policy before any database request',async()=>{const rpc=vi.fn();await expect(saveWorkspacePolicy({rpc} as never,'w',{credentials:'ALLOW'} as never,1)).rejects.toThrow('invalid');expect(rpc).not.toHaveBeenCalled()});
});
describe('team policy migration authorization',()=>{const sql=readFileSync(join(process.cwd(),'supabase','migrations','202609260002_team_policy.sql'),'utf8');it('allows members to read but only owner/admin to update through RPC',()=>{expect(sql).toContain('members read team policy');expect(sql).toMatch(/role in \('owner','admin'\)/);expect(sql).toContain('revoke all on function public.update_workspace_policy');expect(sql).not.toMatch(/create policy[^;]+for update/is)});it('validates exact categories and supported actions server-side',()=>{for(const category of ['credentials','email','phone','internalIp','internalUrl','publicUrl','qr','metadata'])expect(sql).toContain(category);for(const action of ['BLOCK','PROTECT','WARN','ALLOW'])expect(sql).toContain(action);expect(sql).toContain('count(*)=8')});it('contains no screenshot-content schema',()=>{for(const forbidden of ['ocr_text','finding_description','protected_image','image_blob','qr_payload'])expect(sql).not.toContain(forbidden)})});
describe('scanner policy wiring',()=>{it('passes one effective team policy and version to both scanner modes',()=>{const app=readFileSync(join(process.cwd(),'src','App.tsx'),'utf8'),batch=readFileSync(join(process.cwd(),'src','batch','BatchMode.tsx'),'utf8');expect(app).toContain('teamPolicy??getPolicy');expect(app).toContain('effectivePolicy={teamPolicy}');expect(batch).toContain('effectivePolicy??getPolicy');expect(app).toContain('invalidatePolicyResult();')})});
