// @vitest-environment jsdom
import { StrictMode, act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { Finding } from '../types';
import type { Policy } from '../policy/types';
const controls=vi.hoisted(()=>({scan:vi.fn(),protectedBlob:new Blob(['protected'],{type:'image/png'})}));
vi.mock('../utils/image',()=>({loadImage:vi.fn(async()=>({width:640,height:360,close:vi.fn()})),protect:vi.fn(async()=>controls.protectedBlob)}));
vi.mock('../detection/scan',()=>({scan:controls.scan,logDevelopmentScanError:vi.fn(),ScanError:class ScanError extends Error{}}));
import App from '../App';
import { Shell } from '../app/SaaSApp';
const internal:Finding={id:'internal',type:'Internal URL',category:'network',severity:'SENSITIVE',confidence:99,maskedPreview:'http://internal',source:'ocr',description:'internal',selected:false,fingerprint:'internal',box:{x:1,y:1,width:10,height:10}};
const v1:Policy={credentials:'BLOCK',email:'PROTECT',phone:'PROTECT',internalIp:'WARN',internalUrl:'WARN',publicUrl:'ALLOW',qr:'WARN',metadata:'WARN'};
const v2:Policy={...v1,internalUrl:'PROTECT'};
const mounted:{root:Root;container:HTMLDivElement}[]=[];
function button(c:HTMLElement,label:string){return[...c.querySelectorAll('button')].find(b=>b.textContent?.includes(label)) as HTMLButtonElement|undefined}
async function click(c:HTMLElement,label:string){const b=button(c,label);if(!b)throw new Error('Missing '+label);await act(async()=>b.click())}
async function paste(){const file=new File(['source'],'source.png',{type:'image/png'}),event=new Event('paste',{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:{items:[{kind:'file',type:file.type,getAsFile:()=>file}]}});await act(async()=>window.dispatchEvent(event))}
async function mount(element:React.ReactNode){const container=document.createElement('div');document.body.append(container);const root=createRoot(container);mounted.push({root,container});await act(async()=>root.render(<StrictMode>{element}</StrictMode>));return{root,container}}
describe('team policy session lifecycle',()=>{
 beforeEach(()=>{(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;controls.scan.mockReset().mockResolvedValueOnce({findings:[internal]}).mockResolvedValue({findings:[]});let id=0;vi.spyOn(URL,'createObjectURL').mockImplementation(()=>`blob:test/${++id}`);vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});Object.defineProperty(globalThis,'ClipboardItem',{configurable:true,value:class{}});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{write:vi.fn().mockResolvedValue(undefined)}})});
 afterEach(async()=>{for(const item of mounted.splice(0))await act(async()=>item.root.unmount());document.body.textContent='';vi.restoreAllMocks()});
 it('retains source and OCR findings but invalidates every sharing artifact when policy version changes',async()=>{const activity=vi.fn().mockResolvedValue(undefined);const{root,container}=await mount(<App teamPolicy={v1} teamPolicyVersion={1} onActivity={activity}/>);await paste();const originalSrc=(container.querySelector('img[alt="Selected image preview"]') as HTMLImageElement).src;await click(container,'Protect');await click(container,'Protect & Verify');await click(container,'Approve & Copy');expect(container.textContent).toContain('Ready to Share');expect(controls.scan).toHaveBeenCalledTimes(2);await act(async()=>root.render(<StrictMode><App teamPolicy={v2} teamPolicyVersion={2} onActivity={activity}/></StrictMode>));expect(container.textContent).toContain('Team policy changed to version 2');expect(container.textContent).toContain('Internal URL');expect(container.textContent).toContain('Policy: PROTECT');expect(container.textContent).toContain('source.png');expect((container.querySelector('img[alt="Selected image preview"]') as HTMLImageElement).src).toBe(originalSrc);expect(controls.scan).toHaveBeenCalledTimes(2);expect(activity).toHaveBeenCalledTimes(2);expect(container.textContent).not.toContain('Ready to Share');expect(button(container,'Copy Safe Image')).toBeUndefined();expect(button(container,'Export protected image')).toBeUndefined();await click(container,'Protect & Verify');await click(container,'Approve & Copy');expect(container.textContent).toContain('Ready to Share');expect(button(container,'Export protected image')?.disabled).toBe(false);expect(activity).toHaveBeenCalledTimes(4)});
 it('keeps local sharing authorization when activity storage fails',async()=>{const activity=vi.fn().mockRejectedValue(new Error('database'));const{container}=await mount(<App teamPolicy={v2} teamPolicyVersion={2} onActivity={activity}/>);await paste();await click(container,'Protect & Verify');await click(container,'Approve & Copy');expect(container.textContent).toContain('Ready to Share');expect(container.textContent).toContain('Activity record could not be saved.');expect(button(container,'Export protected image')?.disabled).toBe(false)});
 it('keeps Web Scanner state mounted while Batch remains an internal scanner mode',async()=>{const range=vi.fn().mockResolvedValue({data:[],error:null}),order=vi.fn(()=>({range})),eq=vi.fn(()=>({order})),select=vi.fn(()=>({eq}));const client={from:vi.fn(()=>({select})),rpc:vi.fn().mockResolvedValue({data:[],error:null}),auth:{signOut:vi.fn()}} as never;const teamPolicy={workspaceId:'w',policy:v1,version:1,updatedAt:'now',updatedBy:'u'};const{container}=await mount(<Shell client={client} session={{user:{email:'owner@example.com'}} as never} workspace={{id:'w',name:'Team',createdBy:'u',role:'owner'}} teamPolicy={teamPolicy} onPolicyChange={()=>{}}/>);expect(container.textContent).toContain('DASHBOARD');await click(container,'Web Scanner');await paste();expect(container.textContent).toContain('source.png');expect(controls.scan).toHaveBeenCalledOnce();await click(container,'Batch Screenshots');expect(container.textContent).toContain('Protect multiple screenshots');expect(button(container,'Batch Screenshots')?.getAttribute('aria-pressed')).toBe('true');await click(container,'Single Screenshot');expect(container.textContent).toContain('source.png');expect(container.textContent).toContain('Internal URL');await click(container,'Team');await click(container,'Web Scanner');expect(container.textContent).toContain('source.png');expect(controls.scan).toHaveBeenCalledOnce()});
});
