import { describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadMembers } from '../workspace/service';

describe('workspace member loading',()=>{
 it('loads safe roster rows through the authorized RPC without a profile embed',async()=>{const rpc=vi.fn().mockResolvedValue({data:[{user_id:'owner-1',display_name:'Owner',email:'owner@example.com',role:'owner',created_at:'now'}],error:null});expect(await loadMembers({rpc} as never,'workspace-1')).toEqual([{userId:'owner-1',role:'owner',email:'owner@example.com',displayName:'Owner'}]);expect(rpc).toHaveBeenCalledWith('list_workspace_members',{target_workspace:'workspace-1'})});
 it('uses account email when no display name exists',async()=>{const rpc=vi.fn().mockResolvedValue({data:[{user_id:'member-1',display_name:null,email:'member@example.com',role:'member',created_at:'now'}],error:null});expect((await loadMembers({rpc} as never,'workspace-1'))[0].displayName).toBe('member@example.com')});
 it('accepts otherwise-valid nullable identity fields from the RPC',async()=>{const rpc=vi.fn().mockResolvedValue({data:[{user_id:'member-1',display_name:null,email:null,role:'member',created_at:'now'}],error:null});expect((await loadMembers({rpc} as never,'workspace-1'))[0]).toMatchObject({displayName:'Workspace member',role:'member'})});
 it('keeps a denied or failed RPC response generic',async()=>{const rpc=vi.fn().mockResolvedValue({data:null,error:{code:'42804',message:'structure of query does not match function result type'}});await expect(loadMembers({rpc} as never,'workspace-1')).rejects.toThrow('Workspace members could not be loaded.')});
 it('casts auth.users email to the exact declared text return type in the forward fix',()=>{const sql=readFileSync(join(process.cwd(),'supabase','migrations','202609260005_fix_workspace_member_roster.sql'),'utf8');expect(sql).toContain('create or replace function public.list_workspace_members');expect(sql).toContain('returns table(user_id uuid,display_name text,email text,role text,created_at timestamptz)');expect(sql).toContain('au.email::text');expect(sql).toContain('if not public.is_workspace_member(target_workspace)');expect(sql).toContain('grant execute on function public.list_workspace_members(uuid) to authenticated')});
 it('retains least-privilege roster and membership security',()=>{const foundation=readFileSync(join(process.cwd(),'supabase','migrations','202609260001_saas_foundation.sql'),'utf8'),invitations=readFileSync(join(process.cwd(),'supabase','migrations','202609260004_workspace_invitations.sql'),'utf8');expect(foundation).toContain('create policy "members read memberships"');expect(invitations).toContain('if not public.is_workspace_member(target_workspace)');expect(invitations).toContain('join auth.users au on au.id=wm.user_id')});
});
