import type { Finding } from '../types';
import type { Policy, PolicyAction } from '../policy/types';
import { actionForFinding } from '../policy/evaluatePolicy';
import type { BatchItem } from '../batch/model';
import { isReleaseEligible } from '../batch/model';
import type { ActionCounts, BatchPrivacyReport, ReportCount, ReviewState, SinglePrivacyReport, VerificationState } from './types';

const SAFE_TYPES=new Set(['API Key','API Token','Access Token','Bearer Token','Password','AWS Access Key','AWS Secret Access Key','Secret','Generic Credential','Database Connection String','Credential-bearing URL','Email','Phone','Internal URL','Public URL','Internal IP','Public IP','QR code','Date and time','Device','Location','Software']);
const zeroActions=():ActionCounts=>({BLOCK:0,PROTECT:0,WARN:0,ALLOW:0});
function safeType(type:string){return SAFE_TYPES.has(type)?type:'Other finding';}
function findingCounts(findings:Finding[]):ReportCount[]{const counts=new Map<string,number>();for(const finding of findings){const label=safeType(finding.type);counts.set(label,(counts.get(label)??0)+1);}return[...counts].sort(([a],[b])=>a.localeCompare(b)).map(([label,count])=>({label,count}));}
function actionCounts(findings:Finding[],policy:Policy):ActionCounts{return findings.reduce((counts,finding)=>{counts[actionForFinding(finding,policy)]++;return counts;},zeroActions());}
function secureRandom(){if(globalThis.crypto?.getRandomValues){const value=new Uint32Array(1);globalThis.crypto.getRandomValues(value);return value[0]/0x100000000;}return Math.random();}
function id(now:Date,random:()=>number){const date=now.toISOString().slice(0,10).replace(/-/g,'');let suffix='';for(let i=0;i<6;i++)suffix+='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(random()*32)];return`SSR-${date}-${suffix}`;}
function verificationState(current:boolean,passed:boolean|undefined):VerificationState{return!current?'Not run':passed?'Passed':'Failed';}
function reviewState(current:boolean,passed:boolean,approved:boolean):ReviewState{return!current||!passed?'Not available':approved?'Approved':'Awaiting review';}
export type SingleReportInput={profile:string;workflowStatus:string;findings:Finding[];policy:Policy;selectedForProtection:number;verifiedRemoved:number;verificationCurrent:boolean;verificationPassed:boolean;verifiedFindings:Finding[];approved:boolean;now?:Date;random?:()=>number};
export function buildSingleReport(input:SingleReportInput):SinglePrivacyReport{const now=input.now??new Date(),verification=verificationState(input.verificationCurrent,input.verificationPassed),review=reviewState(input.verificationCurrent,input.verificationPassed,input.approved);return{kind:'single',title:'SafeShare Privacy Check Report',info:{reportId:id(now,input.random??secureRandom),generated:now.toLocaleString(),profile:input.profile,workflowStatus:input.workflowStatus,findings:findingCounts(input.findings),actions:actionCounts(input.findings,input.policy),selectedForProtection:input.selectedForProtection,verifiedRemoved:input.verifiedRemoved,verification,remaining:input.verificationCurrent?actionCounts(input.verifiedFindings,input.policy):zeroActions(),review}};}
export type BatchReportInput={profile:string;items:BatchItem[];policy:Policy;now?:Date;random?:()=>number};
function batchVerification(item:BatchItem):VerificationState{return item.verification?item.verification.ready?'Passed':'Failed':'Not run';}
function batchReview(item:BatchItem):ReviewState{return item.verification?.ready?(isReleaseEligible(item)?'Approved':'Awaiting review'):'Not available';}
export function buildBatchReport(input:BatchReportInput):BatchPrivacyReport{const now=input.now??new Date(),findings=input.items.flatMap(item=>item.findings),rows=input.items.map((item,index)=>({item:`Screenshot ${String(index+1).padStart(2,'0')}`,findings:item.findings.length,actions:actionCounts(item.findings,input.policy),verification:batchVerification(item),review:batchReview(item),status:item.status==='ready'?'Ready':item.status==='awaiting-review'?'Awaiting review':item.status==='no-findings'?'No sensitive findings':item.status==='needs-protection'?'Needs protection':item.status==='needs-review'?'Needs review':item.status==='failed'?'Failed':'Not completed'}));const actions=actionCounts(findings,input.policy),approved=rows.filter(row=>row.review==='Approved').length,awaitingReview=rows.filter(row=>row.review==='Awaiting review').length,verificationPassed=rows.filter(row=>row.verification==='Passed').length;return{kind:'batch',title:'SafeShare Batch Privacy Check Report',reportId:id(now,input.random??secureRandom),generated:now.toLocaleString(),profile:input.profile,workflowStatus:input.items.length?`${approved} approved, ${awaitingReview} awaiting review, ${input.items.length-approved-awaitingReview} need attention`:'No screenshots processed',findings:findingCounts(findings),actions,processed:input.items.filter(item=>item.status!=='waiting'&&item.status!=='scanning').length,approved,awaitingReview,needsAttention:input.items.length-approved-awaitingReview,verificationPassed,verificationNeedsAttention:input.items.length-verificationPassed,rows};}
