import type { PrivacyReportData } from './types';

const DISCLAIMER='SafeShare reports the results of automated checks performed using the active sharing policy. Automated detection may produce false positives or false negatives and cannot guarantee that every sensitive exposure has been identified.';
const CONTENT_NOTICE='This report does not include detected sensitive values or screenshot content.';
function actionLines(actions:{BLOCK:number;PROTECT:number;WARN:number;ALLOW:number}){return [`BLOCK: ${actions.BLOCK}`,`PROTECT: ${actions.PROTECT}`,`WARN: ${actions.WARN}`,`ALLOW: ${actions.ALLOW}`];}
export function reportText(report:PrivacyReportData):string{const lines=[report.title,'',`Report ID: ${report.kind==='single'?report.info.reportId:report.reportId}`,`Generated: ${report.kind==='single'?report.info.generated:report.generated}`,`Sharing Profile: ${report.kind==='single'?report.info.profile:report.profile}`,''];if(report.kind==='single'){const info=report.info;lines.push(`Workflow Status: ${info.workflowStatus}`,'','Findings Summary',...(info.findings.length?info.findings.map(row=>`${row.label}: ${row.count}`):['No findings detected']),'','Policy Summary',...actionLines(info.actions),'',`Selected for protection: ${info.selectedForProtection}`,`Protected findings verified removed: ${info.verifiedRemoved}`,'','Verification',`Verification status: ${info.verification}`,...actionLines(info.remaining).map(line=>`Remaining ${line}`),'','Human Review',`Review status: ${info.review}`);}else{lines.push(`Workflow Status: ${report.workflowStatus}`,`Screenshots processed: ${report.processed}`,`Approved for sharing: ${report.approved}`,`Awaiting review: ${report.awaitingReview}`,`Needs attention: ${report.needsAttention}`,'','Findings Summary',...(report.findings.length?report.findings.map(row=>`${row.label}: ${row.count}`):['No findings detected']),'','Policy Actions',...actionLines(report.actions),'',`Verification passed: ${report.verificationPassed}`,`Verification failed or needs attention: ${report.verificationNeedsAttention}`,'','Per-image status','Item | Findings | BLOCK | PROTECT | WARN | ALLOW | Verification | Review | Final status',...report.rows.map(row=>`${row.item} | ${row.findings} | ${row.actions.BLOCK} | ${row.actions.PROTECT} | ${row.actions.WARN} | ${row.actions.ALLOW} | ${row.verification} | ${row.review} | ${row.status}`));}lines.push('','Limitations',DISCLAIMER,CONTENT_NOTICE,'','Generated locally by SafeShare');return lines.join('\n');}
function ascii(value:string){return value.normalize('NFKD').replace(/[^\x20-\x7E\n]/g,'-');}
function escapePdf(value:string){return value.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
export function createReportPdf(report:PrivacyReportData):Blob{const source=ascii(reportText(report)),wrapped:string[]=[];for(const raw of source.split('\n')){if(!raw){wrapped.push('');continue;}for(let rest=raw;rest.length;rest=rest.slice(92))wrapped.push(rest.slice(0,92));}const pages:Array<string[]>=[];for(let index=0;index<wrapped.length;index+=48)pages.push(wrapped.slice(index,index+48));const objects:string[]=['',''];const fontId=3+pages.length*2;for(let index=0;index<pages.length;index++){const pageId=3+index*2,contentId=pageId+1,stream=`BT\n/F1 10 Tf\n50 790 Td\n14 TL\n${pages[index].map(line=>`(${escapePdf(line)}) Tj T*`).join('\n')}\nET`;objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;}objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[2]=`<< /Type /Pages /Kids [${pages.map((_,index)=>`${3+index*2} 0 R`).join(' ')}] /Count ${pages.length} >>`;objects[fontId]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';let pdf='%PDF-1.4\n',offsets=[0];for(let index=1;index<objects.length;index++){if(!objects[index])continue;offsets[index]=pdf.length;pdf+=`${index} 0 obj\n${objects[index]}\nendobj\n`;}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let index=1;index<objects.length;index++)pdf+=`${String(offsets[index]??0).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'});}
export function startReportDownload(report:PrivacyReportData,filename:string):string{const url=URL.createObjectURL(createReportPdf(report)),anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();return url;}
