import { useEffect, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { POLICY_ACTIONS, POLICY_CATEGORIES, type Policy, type PolicyAction } from '../policy/types';
import type { Workspace } from './types';
import { saveWorkspacePolicy, type WorkspacePolicy } from './policyService';
import { buildPolicyActivity } from '../activity/builder';
import type { SafeActivityInput } from '../activity/types';
const labels={credentials:'Credentials',email:'Email',phone:'Phone',internalIp:'Internal IP',internalUrl:'Internal URL',publicUrl:'Public URL',qr:'QR Code',metadata:'Metadata'} as const;
export function TeamPolicy({client,workspace,value,onChange,onActivity}:{client:SupabaseClient;workspace:Workspace;value:WorkspacePolicy;onChange:(value:WorkspacePolicy)=>void;onActivity?:(event:SafeActivityInput)=>Promise<void>}){const[policy,setPolicy]=useState<Policy>(value.policy),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const editable=workspace.role==='owner'||workspace.role==='admin';useEffect(()=>setPolicy(value.policy),[value]);async function save(){setBusy(true);setMessage('');try{const saved=await saveWorkspacePolicy(client,workspace.id,policy,value.version);onChange(saved);setMessage('Team policy saved. Scanner authorization now uses this version.');if(onActivity)try{await onActivity(buildPolicyActivity(saved.version));}catch{setMessage('Team policy saved, but activity record could not be saved.')}}catch{setMessage('Team policy could not be saved. Reload and try again.')}finally{setBusy(false)}}return <section className="team-policy"><h3>Team Policy</h3><p>Choose how SafeShare handles each type of information before screenshots are shared.</p><p className="policy-owner-note">{editable?'Owners and admins can update this policy.':'Managed by your workspace. Your access is read-only.'} Version {value.version}.</p><div className="policy-legend" aria-label="Policy action meanings"><span><b>BLOCK</b> Sharing must stop</span><span><b>PROTECT</b> Remove before sharing</span><span><b>WARN</b> Requires attention</span><span><b>ALLOW</b> No protection required</span></div><div className="custom-policy">{POLICY_CATEGORIES.map(category=><label key={category}><span>{labels[category]}</span><select disabled={!editable||busy} value={policy[category]} onChange={e=>setPolicy({...policy,[category]:e.target.value as PolicyAction})}>{POLICY_ACTIONS.map(action=><option key={action}>{action}</option>)}</select></label>)}</div>{message&&<div className="auth-message" role="status">{message}</div>}{editable&&<button className="primary" disabled={busy||JSON.stringify(policy)===JSON.stringify(value.policy)} onClick={()=>void save()}>{busy?'Saving policy...':'Save team policy'}</button>}</section>}
