type PublicSiteProps={onNavigate:(path:string)=>void};
export const PILOT_HREF='mailto:?subject=SafeShare%20Windows%20Private%20Pilot&body=Tell%20us%20about%20your%20team%20and%20screenshot%20workflow.';
const workflow=[['CAPTURE','Screenshot taken'],['CHECK','Checked locally'],['PROTECT','Sensitive data protected'],['VERIFY','Protected image rescanned'],['SHARE','Employee approves']];
const risks=['API keys','Customer information','Internal URLs','Credentials'];
export function PublicSite({onNavigate}:PublicSiteProps){return <div className="public-site">
  <header className="public-nav"><a className="public-brand" href="#top" aria-label="SafeShare home"><span className="public-brand-mark">S</span><span>SafeShare</span></a><nav aria-label="Public website"><a href="#how">How it works</a><a href="#product">Product</a><a href="#privacy">Privacy</a></nav><button className="public-signin" onClick={()=>onNavigate('/login')}>Company Console <span aria-hidden="true">/</span> Sign in</button></header>
  <main id="top">
    <section className="public-hero"><div className="public-hero-copy"><span className="public-kicker">LOCAL SCREENSHOT PROTECTION FOR SOFTWARE TEAMS</span><h1>Stop sensitive screenshots before they leave your company.</h1><p>SafeShare checks screenshots locally, protects sensitive information, and verifies the protected image before employees share it.</p><div className="public-hero-actions"><a className="public-primary" href={PILOT_HREF}>Start Private Pilot</a><a className="public-secondary" href="#how">See How It Works</a></div><small>Currently available through controlled Windows private pilots.</small></div>
      <div className="public-product-visual" aria-label="Synthetic SafeShare protection example"><div className="visual-window-bar"><span></span><span></span><span></span><b>SafeShare Agent</b></div><div className="visual-policy"><span>Team Policy v7</span><strong>Protected locally</strong></div><div className="visual-code"><p><em>API_KEY</em><b>**********</b><i>BLOCK</i></p><p><em>CUSTOMER_EMAIL</em><b>ananya.demo@example.com</b><i>WARN</i></p><p><em>INTERNAL_API</em><b>**********</b><i>PROTECT</i></p><p><em>PUBLIC_SITE</em><b>https://example.com</b><i>ALLOW</i></p></div><div className="visual-verified"><span>Verification passed</span><strong>Ready for employee review</strong></div></div>
    </section>
    <section className="public-section compact-problem"><div className="public-section-heading"><span className="public-kicker">THE SHARING GAP</span><h2>One screenshot can expose more than expected.</h2></div><div className="risk-grid">{risks.map(item=><article key={item}>{item}</article>)}</div></section>
    <section className="public-section public-workflow" id="how"><div className="public-section-heading centered"><span className="public-kicker">HOW IT WORKS</span><h2>From screenshot to safer share.</h2></div><div className="workflow-steps">{workflow.map(([title,copy],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="public-section" id="product"><div className="public-section-heading"><span className="public-kicker">THE PRODUCT</span><h2>Protection for employees. Control for companies.</h2></div><div className="product-cards two-up"><article className="featured"><span className="card-label">EMPLOYEE SIDE</span><h3>SafeShare Agent</h3><p>Checks screenshots locally before sharing.</p></article><article><span className="card-label">COMPANY CONTROL</span><h3>SafeShare Console</h3><p>Manage Team Policy and view privacy-safe workflow activity.</p></article></div><p className="manual-workflow">A browser-based Web Scanner is available for occasional manual workflows.</p></section>
    <section className="public-section public-privacy" id="privacy"><div><span className="public-kicker">SECURITY &amp; PRIVACY</span><h2>Built around local processing.</h2></div><ul className="privacy-points"><li>Screenshot processing stays on the employee's device.</li><li>Company sharing policy is centrally managed.</li><li>Console receives privacy-safe workflow activity.</li></ul></section>
    <section className="public-closing"><span className="public-kicker">PRIVATE PILOT</span><h2>Try SafeShare with your team.</h2><p>Controlled Windows private pilots for software teams.</p><div><a className="public-primary light" href={PILOT_HREF}>Start Private Pilot</a></div></section>
  </main>
  <footer className="public-footer"><div><strong>SafeShare</strong><span>Scan before you share.</span></div><nav aria-label="Footer"><a href="#how">How it works</a><a href="#product">Product</a><a href="#privacy">Privacy</a><button onClick={()=>onNavigate('/login')}>Company Sign In</button></nav><small>SafeShare private pilot</small></footer>
</div>}