type PublicSiteProps={onNavigate:(path:string)=>void};
export const PILOT_HREF='mailto:?subject=SafeShare%20Windows%20Private%20Pilot&body=Tell%20us%20about%20your%20team%20and%20screenshot%20workflow.';
const workflow=[['CAPTURE','Take a screenshot normally.'],['CHECK','SafeShare Agent checks supported screenshots locally.'],['PROTECT','Team Policy determines how findings are handled.'],['VERIFY','SafeShare rescans the protected output.'],['SHARE','The employee reviews and approves the image.']];
const uses=[['QA & Testing Teams','Share defect evidence without overlooking visible test credentials.'],['Support Teams','Review screenshots before adding them to customer conversations.'],['Software Agencies','Apply a consistent sharing policy across client work.'],['Engineering Teams','Protect internal endpoints and credentials in technical discussions.'],['Technical Support / IT','Check diagnostic screenshots before they move between teams.'],['Documentation Teams','Prepare screenshots for guides and public documentation.']];
export function PublicSite({onNavigate}:PublicSiteProps){return <div className="public-site">
  <header className="public-nav"><a className="public-brand" href="#top" aria-label="SafeShare home"><span className="public-brand-mark">S</span><span>SafeShare</span></a><nav aria-label="Public website"><a href="#product">Product</a><a href="#how">How it works</a><a href="#privacy">Security &amp; Privacy</a><a href="#pilot">Windows Pilot</a></nav><button className="public-signin" onClick={()=>onNavigate('/login')}>Company Console <span aria-hidden="true">/</span> Sign in</button></header>
  <main id="top">
    <section className="public-hero"><div className="public-hero-copy"><span className="public-kicker">LOCAL SCREENSHOT PROTECTION FOR SOFTWARE TEAMS</span><h1>Stop sensitive screenshots before they leave your company.</h1><p>SafeShare checks screenshots locally on employee Windows devices, applies your company's sharing policy, protects sensitive information, and verifies the protected image before it is shared.</p><div className="public-hero-actions"><a className="public-primary" href={PILOT_HREF}>Start Private Pilot</a><a className="public-secondary" href="#how">See how it works</a></div><small>Currently available through controlled Windows private pilots.</small></div>
      <div className="public-product-visual" aria-label="Synthetic SafeShare protection example"><div className="visual-window-bar"><span></span><span></span><span></span><b>SafeShare Agent</b></div><div className="visual-policy"><span>Team Policy v7</span><strong>Protected locally</strong></div><div className="visual-code"><p><em>API_KEY</em><b>**********</b><i>BLOCK</i></p><p><em>CUSTOMER_EMAIL</em><b>ananya.demo@example.com</b><i>WARN</i></p><p><em>INTERNAL_API</em><b>**********</b><i>PROTECT</i></p><p><em>PUBLIC_SITE</em><b>https://example.com</b><i>ALLOW</i></p></div><div className="visual-verified"><span>Verification passed</span><strong>Ready for employee review</strong></div></div>
    </section>
    <section className="public-trust-strip" aria-label="SafeShare product principles"><span>Windows employee protection</span><span>Company-managed policy</span><span>Local screenshot processing</span><span>Verified protected output</span></section>
    <section className="public-section public-problem"><div className="public-section-heading"><span className="public-kicker">THE SHARING GAP</span><h2>Screenshots move quickly. Sensitive context can move with them.</h2><p>Software teams use screenshots in support tickets, collaboration tools, bug reports, client conversations, documentation, and AI tools. SafeShare adds a review point before sharing.</p></div><div className="problem-grid"><article><h3>What can appear</h3><p>Credentials, customer information, internal URLs, internal IP addresses, QR codes, and metadata.</p></article><article><h3>Why it gets missed</h3><p>A useful screenshot can include details outside the area someone intended to discuss.</p></article><article><h3>Where SafeShare helps</h3><p>It checks supported screenshot workflows and brings policy, protection, verification, and human review together.</p></article></div></section>
    <section className="public-section public-workflow" id="how"><div className="public-section-heading centered"><span className="public-kicker">HOW SAFESHARE WORKS</span><h2>A clear checkpoint between capture and share.</h2><p>SafeShare supports employee judgment with a repeatable company workflow. Detection has practical limits and does not guarantee every sensitive item will be found.</p></div><div className="workflow-steps">{workflow.map(([title,copy],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="public-section" id="product"><div className="public-section-heading"><span className="public-kicker">ONE PRODUCT, THREE SURFACES</span><h2>Protection for employees. Control for companies.</h2></div><div className="product-cards"><article className="featured"><span className="card-label">EMPLOYEE SIDE</span><h3>SafeShare Agent</h3><p>A Windows application for supported screenshot and clipboard-image workflows.</p><ul><li>Local OCR and detection</li><li>Company-managed Team Policy</li><li>Protect &amp; Verify</li><li>Human review and approval</li></ul></article><article><span className="card-label">COMPANY CONTROL</span><h3>Team Policy + Console</h3><p>Manage workspace rules without moving screenshot contents into the Console.</p><ul><li>BLOCK / PROTECT / WARN / ALLOW</li><li>Team and workspace management</li><li>Policy versioning</li><li>Privacy-safe Activity</li></ul></article><article><span className="card-label">MANUAL OPTION</span><h3>Web Scanner</h3><p>Manual browser-based checking for occasional Single and Batch workflows.</p><ul><li>Upload or paste</li><li>Local browser processing</li><li>Protection and verification</li><li>Copy or download after review</li></ul></article></div></section>
    <section className="public-section public-privacy" id="privacy"><div><span className="public-kicker">SECURITY &amp; PRIVACY</span><h2>Screenshot processing stays on the employee's device.</h2><p>Screenshot OCR and detection run locally. Screenshot contents are not intentionally sent to SafeShare's control plane.</p><p>Companies can centrally manage Team Policy while Console Activity is designed to contain privacy-safe workflow metadata rather than screenshot contents or detected values.</p></div><div className="privacy-boundary"><h3>Designed to stay local</h3><ul><li>Screenshot pixels</li><li>OCR text and word geometry</li><li>Detected and protected values</li><li>Protected image output</li></ul><h3>Company control plane</h3><ul><li>Workspace and membership</li><li>Team Policy and version</li><li>Privacy-safe workflow status</li></ul></div></section>
    <section className="public-section console-preview-section"><div className="public-section-heading"><span className="public-kicker">COMPANY CONSOLE</span><h2>Agent protects employees. Console controls the rules.</h2><p>Company administrators manage teams and policy, then review privacy-safe workflow Activity.</p></div><div className="console-preview"><div className="console-preview-nav"><strong>SafeShare Console</strong><span>Dashboard</span><span>Team</span><span>Policy</span><span>Activity</span></div><div className="console-preview-body"><div className="console-preview-title"><div><small>DASHBOARD</small><h3>Software Team Workspace</h3></div><b>OWNER</b></div><div className="console-preview-metrics"><article><span>Screenshots verified</span></article><article><span>Approved for sharing</span></article><article><span>Findings protected</span></article><article><span>Active Team Policy</span><strong>v7</strong></article></div><div className="console-preview-panels"><article><h4>SafeShare Agent protection</h4><p>Capture / Check / Protect / Verify / Share</p></article><article><h4>Privacy-safe Activity</h4><p>Workflow events, policy versions, and review status.</p></article></div></div></div><p className="synthetic-note">Illustrative Console interface.</p></section>
    <section className="public-section"><div className="public-section-heading centered"><span className="public-kicker">BUILT FOR SOFTWARE WORK</span><h2>Useful wherever technical screenshots are shared.</h2></div><div className="use-grid">{uses.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="public-section pilot-section" id="pilot"><div><span className="public-kicker">WINDOWS PRIVATE PILOT</span><h2>SafeShare Windows Private Pilot</h2><p>SafeShare is currently available for controlled Windows pilots. We work with a small number of software teams to validate fit, deployment, and employee workflow.</p><p>Pilot access and Windows Agent deployment are coordinated directly with each participating team.</p></div><a className="public-primary" href={PILOT_HREF}>Start Private Pilot</a></section>
    <section className="public-closing"><span className="public-kicker">PRIVATE PILOT</span><h2>See how SafeShare fits your team's screenshot workflow.</h2><p>We're opening a small number of Windows private pilots for software teams.</p><div><a className="public-primary light" href={PILOT_HREF}>Start Private Pilot</a><button className="public-secondary dark" onClick={()=>onNavigate('/login')}>Company Sign In</button></div></section>
  </main>
  <footer className="public-footer"><div><strong>SafeShare</strong><span>Scan before you share.</span></div><nav aria-label="Footer"><a href="#product">Product</a><a href="#how">How it works</a><a href="#privacy">Security &amp; Privacy</a><a href="#pilot">Windows Pilot</a><button onClick={()=>onNavigate('/login')}>Company Sign In</button></nav><small>SafeShare private pilot</small></footer>
</div>}
