import { describe,expect,it,vi } from 'vitest';
import type { SupabaseClient } from '@supabase/supabase-js';
import { PROFILES } from '../../../src/policy/profiles';
import { SupabaseAgentControlPlane } from './adapter';
import { AuthenticationError, ControlPlaneUnavailableError, InvalidTeamPolicyError } from './types';

function client(overrides:Record<string,unknown>={}):SupabaseClient{return{auth:{signInWithPassword:vi.fn(),signOut:vi.fn(),getSession:vi.fn()},from:vi.fn(),...overrides} as unknown as SupabaseClient;}
describe('Agent Supabase control-plane adapter',()=>{
  it('authenticates an existing account without retaining or reshaping the password',async()=>{const signInWithPassword=vi.fn(async()=>({data:{session:{user:{id:'user-a',email:'member@example.com'}}},error:null})),value=client({auth:{signInWithPassword,signOut:vi.fn(),getSession:vi.fn()}}),adapter=new SupabaseAgentControlPlane(value);await expect(adapter.signIn(' member@example.com ','temporary-password')).resolves.toEqual({id:'user-a',email:'member@example.com'});expect(signInWithPassword).toHaveBeenCalledWith({email:'member@example.com',password:'temporary-password'});expect(JSON.stringify(adapter)).not.toContain('temporary-password')});
  it('returns a generic authentication failure',async()=>{const value=client({auth:{signInWithPassword:vi.fn(async()=>({data:{session:null},error:{message:'specific'}})),signOut:vi.fn(),getSession:vi.fn()}});await expect(new SupabaseAgentControlPlane(value).signIn('a@b.com','bad-password')).rejects.toBeInstanceOf(AuthenticationError)});
  it.each([['user-member','member'],['user-owner','owner']] as const)('filters discovery to the authenticated %s membership',async(userId,role)=>{const eq=vi.fn(async()=>({data:[{role,workspaces:{id:'workspace-a',name:'Workspace A'}}],error:null})),select=vi.fn(()=>({eq})),getSession=vi.fn(async()=>({data:{session:{user:{id:userId,email:userId+'@example.com'}}},error:null})),value=client({auth:{signInWithPassword:vi.fn(),signOut:vi.fn(),getSession},from:vi.fn(()=>({select}))});await expect(new SupabaseAgentControlPlane(value).listAccessibleWorkspaces()).resolves.toEqual([{id:'workspace-a',name:'Workspace A',role}]);expect(eq).toHaveBeenCalledWith('user_id',userId)});
  it('returns all of one users memberships across different workspaces',async()=>{const eq=vi.fn(async()=>({data:[{role:'member',workspaces:{id:'workspace-a',name:'Workspace A'}},{role:'admin',workspaces:{id:'workspace-b',name:'Workspace B'}}],error:null})),select=vi.fn(()=>({eq})),getSession=vi.fn(async()=>({data:{session:{user:{id:'user-member',email:'member@example.com'}}},error:null})),value=client({auth:{signInWithPassword:vi.fn(),signOut:vi.fn(),getSession},from:vi.fn(()=>({select}))});await expect(new SupabaseAgentControlPlane(value).listAccessibleWorkspaces()).resolves.toEqual([{id:'workspace-a',name:'Workspace A',role:'member'},{id:'workspace-b',name:'Workspace B',role:'admin'}]);expect(eq).toHaveBeenCalledWith('user_id','user-member')});
  it('fails closed when workspace discovery has no authenticated session',async()=>{const value=client({auth:{signInWithPassword:vi.fn(),signOut:vi.fn(),getSession:vi.fn(async()=>({data:{session:null},error:null}))}});await expect(new SupabaseAgentControlPlane(value).listAccessibleWorkspaces()).rejects.toBeInstanceOf(AuthenticationError)});
  it('loads and validates the existing versioned Team Policy row',async()=>{const single=vi.fn(async()=>({data:{workspace_id:'workspace-a',policy:PROFILES.client.policy,version:4,updated_at:'2026-09-28T00:00:00Z'},error:null})),eq=vi.fn(()=>({single})),select=vi.fn(()=>({eq})),value=client({from:vi.fn(()=>({select}))}),workspace={id:'workspace-a',name:'Workspace A',role:'member' as const};await expect(new SupabaseAgentControlPlane(value).getTeamPolicy(workspace)).resolves.toMatchObject({workspaceId:'workspace-a',version:4,policy:PROFILES.client.policy,source:'server'});expect(eq).toHaveBeenCalledWith('workspace_id','workspace-a')});
  it('fails closed for malformed policy and classifies query failure as unavailable',async()=>{const workspace={id:'workspace-a',name:'Workspace A',role:'member' as const};const malformed=client({from:vi.fn(()=>({select:()=>({eq:()=>({single:async()=>({data:{workspace_id:'workspace-a',policy:{email:'ALLOW'},version:1,updated_at:'x'},error:null})})})}))});await expect(new SupabaseAgentControlPlane(malformed).getTeamPolicy(workspace)).rejects.toBeInstanceOf(InvalidTeamPolicyError);const failed=client({from:vi.fn(()=>({select:()=>({eq:()=>({single:async()=>({data:null,error:{message:'offline'}})})})}))});await expect(new SupabaseAgentControlPlane(failed).getTeamPolicy(workspace)).rejects.toBeInstanceOf(ControlPlaneUnavailableError)});
});