import { describe, expect, it } from 'vitest';
import type { Finding } from '../../src/types';
import { PROFILES } from '../../src/policy/profiles';
import type { VerificationReport } from '../../src/verification/verify';
import { approveExact, applyTeamPolicy, beginProtection, canApprove, dismissReview, emptyReviewState, finishVerification, invalidateAuthorization, receiveReview, revokeApproval, clearReviewForSignOut, type ReviewCandidate } from './reviewState';
import type { TeamPolicySnapshot } from './controlPlane/types';

const finding: Finding = { id: 'safe-test', type: 'Email', category: 'personal', severity: 'SENSITIVE', confidence: 99, maskedPreview: 'masked', source: 'ocr', description: 'safe test', selected: true, fingerprint: 'finding' };
const policy=(version=1):TeamPolicySnapshot=>({workspaceId:'workspace-a',workspaceName:'Workspace A',version,policy:PROFILES.client.policy,fetchedAt:'2026-09-28T00:00:00.000Z',source:'server'});
const candidate = (fingerprint: string,teamPolicy=policy()): ReviewCandidate => ({ fingerprint, bytes: Uint8Array.from([1, 2, 3]), findings: [finding],policy:teamPolicy });
const output=(fingerprint='protected',version=1)=>({fingerprint,bytes:Uint8Array.from([4]),findings:[finding],workspaceId:'workspace-a',policyVersion:version});
const passed: VerificationReport = { checks: [{ finding, passed: true }], unresolved: [], reviewCount: 0, ready: true };
const failed: VerificationReport = { checks: [{ finding, passed: false }], unresolved: [finding], reviewCount: 0, ready: false };

describe('M3 policy-bound volatile review lifecycle', () => {
  it('creates review state for an attention-required candidate',()=>{const state=receiveReview(emptyReviewState(),candidate('original'));expect(state.active?.fingerprint).toBe('original');expect(state.active?.policy.version).toBe(1)});
  it('protection invalidates previous output, verification, and approval',()=>{let state=receiveReview(emptyReviewState(),candidate('original'));state=finishVerification(state,output(),passed);state=approveExact(state,'protected');state=beginProtection(state);expect(state.protected).toBeNull();expect(state.verification).toBeNull();expect(state.approvedFingerprint).toBeNull()});
  it('binds verification and approval to exact output and policy version',()=>{let state=receiveReview(emptyReviewState(),candidate('original'));expect(finishVerification(state,output('wrong-version',2),passed)).toBe(state);state=finishVerification(state,output(),passed);expect(canApprove(state)).toBe(true);expect(approveExact(state,'different').approvedFingerprint).toBeNull();expect(approveExact(state,'protected').approvedFingerprint).toBe('protected')});
  it('blocks approval when fresh verification fails',()=>{let state=receiveReview(emptyReviewState(),candidate('original'));state=finishVerification(state,output(),failed);expect(canApprove(state)).toBe(false)});
  it('invalidates verification and approval when Team Policy version changes and reevaluates findings',()=>{let state=receiveReview(emptyReviewState(),candidate('original'));state=approveExact(finishVerification(state,output(),passed),'protected');const warnPolicy={...policy(2),policy:{...PROFILES.client.policy,email:'WARN' as const}};state=applyTeamPolicy(state,warnPolicy);expect(state.active?.policy.version).toBe(2);expect((state.active?.findings[0] as Finding&{policyAction?:string}).policyAction).toBe('WARN');expect(state.protected).toBeNull();expect(state.verification).toBeNull();expect(state.approvedFingerprint).toBeNull();expect(canApprove(state)).toBe(false)});
  it('fails closed by invalidating authorization while retaining the local source review',()=>{let state=receiveReview(emptyReviewState(),candidate('original'));state=finishVerification(state,output(),passed);state=invalidateAuthorization(state);expect(state.active?.fingerprint).toBe('original');expect(state.protected).toBeNull();expect(canApprove(state)).toBe(false)});
  it('preserves active review and promotes only newest pending screenshot with isolated state',()=>{const second=candidate('second'),third=candidate('third');let state=receiveReview(emptyReviewState(),candidate('first'));state=receiveReview(state,second);state=receiveReview(state,third);state=finishVerification(state,output(),passed);state=approveExact(state,'protected');state=dismissReview(state);expect(state.active).toBe(third);expect(state.pending).toBeNull();expect(state.protected).toBeNull();expect(state.verification).toBeNull();expect(state.approvedFingerprint).toBeNull()});
  it('sign out clears original, pending, protected, verification, and approval state',()=>{const active=candidate('active'),pending=candidate('pending');let state=receiveReview(emptyReviewState(),active);state=receiveReview(state,pending);state=approveExact(finishVerification(state,output(),passed),'protected');const activeBytes=active.bytes,pendingBytes=pending.bytes,protectedBytes=state.protected!.bytes;state=clearReviewForSignOut(state);expect(state).toEqual(emptyReviewState());expect([...activeBytes]).toEqual([0,0,0]);expect([...pendingBytes]).toEqual([0,0,0]);expect([...protectedBytes]).toEqual([0])});  it('dismisses without creating clipboard authorization',()=>{const state=dismissReview(receiveReview(emptyReviewState(),candidate('original')));expect(state.active).toBeNull();expect(state.protected).toBeNull()});
  it('revokes approval without changing protected bytes',()=>{let state=receiveReview(emptyReviewState(),candidate('original'));state=finishVerification(state,output(),passed);state=revokeApproval(approveExact(state,'protected'));expect(state.approvedFingerprint).toBeNull();expect(state.protected?.fingerprint).toBe('protected')});
});