import { useState, type FormEvent } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';

type Props={client:SupabaseClient;mode:'signin'|'signup';onNavigate:(path:string)=>void;invitationToken?:string};
function validEmail(value:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);}
export function signupRedirect(invitationToken?:string,origin=window.location.origin):string{
  return invitationToken&&/^[0-9a-f]{64}$/.test(invitationToken)
    ?new URL('/invite/'+invitationToken,origin).href
    :new URL('/',origin).origin;
}
export function AuthForm({client,mode,onNavigate,invitationToken}:Props){
  const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState('');
  const[busy,setBusy]=useState(false),[resendBusy,setResendBusy]=useState(false),[message,setMessage]=useState(''),[confirmationRequired,setConfirmationRequired]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();if(!validEmail(email)||password.length<8){setMessage('Enter a valid email and a password with at least 8 characters.');return;}setBusy(true);setMessage('');setConfirmationRequired(false);try{if(mode==='signup'){const{data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name.trim()||undefined},emailRedirectTo:signupRedirect(invitationToken)}});if(error)throw error;setPassword('');if(!data.session){setConfirmationRequired(true);setMessage('Account created. Check your email to confirm your account.');}}else{const{error}=await client.auth.signInWithPassword({email,password});if(error)throw error;}}catch{setMessage(mode==='signup'?'Account creation could not finish. Check your details and try again.':'Sign in could not finish. Check your email and password.');}finally{setBusy(false);}}
  async function resend(){setResendBusy(true);setMessage('');try{const{error}=await client.auth.resend({type:'signup',email,options:{emailRedirectTo:signupRedirect(invitationToken)}});if(error)throw error;setMessage('Confirmation email sent. Check your inbox.');}catch{setMessage('Confirmation email could not be sent. Please try again.');}finally{setResendBusy(false);}}
  const success=confirmationRequired&&(message.startsWith('Account created.')||message.startsWith('Confirmation email sent.'));
  return <main className="auth-page"><section className="auth-card"><div className="eyebrow">SAFESHARE ACCOUNT</div><h1>{mode==='signup'?'Create account':'Welcome back'}</h1><p>Screenshot analysis continues to run locally in your browser.</p><form onSubmit={submit}>{mode==='signup'&&<label>Display name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='signup'?'new-password':'current-password'} required/></label>{message&&<div className="auth-message" role={success?'status':'alert'}>{message}</div>}<button className="primary wide" disabled={busy||resendBusy}>{busy?(mode==='signup'?'Creating account...':'Signing in...'):(mode==='signup'?'Create account':'Sign in')}</button>{confirmationRequired&&<button type="button" className="secondary wide" disabled={busy||resendBusy} onClick={()=>void resend()}>{resendBusy?'Sending confirmation...':'Resend confirmation email'}</button>}</form><button className="auth-link" onClick={()=>onNavigate(mode==='signup'?'/login':'/signup')}>{mode==='signup'?'Already have an account? Sign in':'New to SafeShare? Create account'}</button></section></main>;
}